### ISSUE TITLE
🎀 Overall Webpage's To-Do List

### ISSUE THREAD

**Issue by FaerieCoder** [FaerieCoder/Horiseon#1]
## User Story 👩🏽‍💻
**AS A** marketing agency
**I WANT** a codebase that follows accessibility standards
**SO THAT** our own site is optimized for search engines

## Acceptance Criteria 📋

- [x] Semantic HTML elements can be found throughout the source code
- [x] HTML elements follow a logical structure independent of styling and positioning
- [x] Image and icon elements contain accessible alt attributes
- [x] Heading attributes fall in sequential order
- [x] Title elements contain a concise, descriptive title

**Comment by FaerieCoder** [comment]
Done! 😁✅
